#!/usr/bin/env bun

import path from "node:path";

let SERVER_URL = process.env.SERVER_URL ?? "http://localhost:3000";

// --- Helpers ---

function fatal(message: string): never {
  console.error(`error: ${message}`);
  process.exit(1);
}

async function apiRequest(method: string, path: string, body?: unknown): Promise<unknown> {
  const url = `${SERVER_URL}${path}`;
  const res = await fetch(url, {
    method,
    headers: body ? { "Content-Type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json();

  if (!res.ok) {
    const code = (data as { error?: { code?: string } }).error?.code ?? res.statusText;
    const msg = (data as { error?: { message?: string } }).error?.message ?? "unknown error";
    fatal(`${code}: ${msg}`);
  }

  return data;
}

function printJson(data: unknown): void {
  console.log(JSON.stringify(data, null, 2));
}

function usage(): never {
  console.log(`context-pages — CLI for Context Pages

Usage:
  context-pages session create  --user <id> --pages <p1,p2,...>
  context-pages session get     <session_id>
  context-pages session delete  <session_id>
  context-pages generate        --user <id> --pages <p1,p2,...> [--output <path>]

Global options:
  --server <url>   Server URL (default: $SERVER_URL or http://localhost:3000)
  --help                 Show this help

Examples:
  context-pages session create --user agent-001 --pages sales,product
  context-pages generate --user agent-001 --pages sales,product,clients
  context-pages generate --user agent-001 --pages sales --output ./project/CLAUDE.md
  context-pages session get abc-123
  context-pages session delete abc-123`);
  process.exit(0);
}

// --- Arg parsing ---

function parseArgs(args: string[]): { positional: string[]; flags: Record<string, string> } {
  const positional: string[] = [];
  const flags: Record<string, string> = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const next = args[i + 1];
      if (next && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = "true";
      }
    } else {
      positional.push(arg);
    }
  }

  return { positional, flags };
}

// --- Commands ---

async function sessionCreate(flags: Record<string, string>): Promise<void> {
  const user = flags.user;
  const pagesRaw = flags.pages;

  if (!user) fatal("--user <id> is required");
  if (!pagesRaw) fatal("--pages <page1,page2,...> is required");

  const pages = pagesRaw.split(",").map((p) => p.trim()).filter(Boolean);
  if (pages.length === 0) fatal("at least one page is required");

  const data = await apiRequest("POST", "/session", { user_id: user, pages });

  printJson(data);
}

async function sessionGet(sessionId: string): Promise<void> {
  if (!sessionId) fatal("<session_id> is required");

  const data = await apiRequest("GET", `/session/${sessionId}`);
  printJson(data);
}

async function sessionDelete(sessionId: string): Promise<void> {
  if (!sessionId) fatal("<session_id> is required");

  const data = await apiRequest("DELETE", `/session/${sessionId}`);
  printJson(data);
}

async function generateClaudeMd(flags: Record<string, string>): Promise<void> {
  const user = flags.user;
  const pagesRaw = flags.pages;
  const output = flags.output ?? "./CLAUDE.md";

  if (!user) fatal("--user <id> is required");
  if (!pagesRaw) fatal("--pages <page1,page2,...> is required");

  const pages = pagesRaw.split(",").map((p) => p.trim()).filter(Boolean);
  if (pages.length === 0) fatal("at least one page is required");

  // Create session via API
  const data = (await apiRequest("POST", "/session", { user_id: user, pages })) as {
    session_id: string;
    expires_at: number;
    context_urls: Record<string, string>;
  };

  // Build CLAUDE.md content
  const urlList = Object.entries(data.context_urls)
    .map(([page, url]) => `- **${page}**: \`${url}\``)
    .join("\n");

  const content = `# Context Pages — Active Session

## Instructions

You have access to context pages via HTTP. When you need information
about any of the available topics, make a GET request to the corresponding URL.
URLs expire at ${new Date(data.expires_at * 1000).toISOString()}.

## How to use the URLs

Use the CURL tool to make GET requests to the URLs.
The content is plain text — read it and use it as context for your task.

If you receive an error, the \`error.code\` field indicates the reason:
- \`token_expired\` (401): the session has expired — ask the user to generate a new one
- \`session_revoked\` (403): the session was revoked
- \`invalid_signature\` (401): the signature is invalid
- \`page_not_found\` (404): the page does not exist

## Available URLs

${urlList}

## Session ID

\`${data.session_id}\`

---
*Auto-generated by Context Pages CLI. Do not edit manually.*
`;

  const resolvedPath = path.resolve(output);
  await Bun.write(resolvedPath, content);

  console.log(`session:   ${data.session_id}`);
  console.log(`expires:   ${new Date(data.expires_at * 1000).toISOString()}`);
  console.log(`pages:     ${pages.join(", ")}`);
  console.log(`written:   ${resolvedPath}`);
}

// --- Main ---

async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);

  if (rawArgs.length === 0 || rawArgs.includes("--help")) {
    usage();
  }

  const { positional, flags } = parseArgs(rawArgs);

  if (flags.server) {
    SERVER_URL = flags.server;
  }

  const command = positional[0];
  const subcommand = positional[1];

  if (command === "session") {
    if (subcommand === "create") {
      await sessionCreate(flags);
    } else if (subcommand === "get") {
      await sessionGet(positional[2]);
    } else if (subcommand === "delete") {
      await sessionDelete(positional[2]);
    } else {
      fatal(`unknown subcommand: session ${subcommand ?? ""}\nUse --help to see available commands.`);
    }
  } else if (command === "generate") {
    await generateClaudeMd(flags);
  } else {
    fatal(`unknown command: ${command}\nUse --help to see available commands.`);
  }
}

main().catch((err) => {
  const msg = err?.message ?? String(err);
  if (msg.includes("Unable to connect") || msg.includes("ECONNREFUSED") || msg.includes("fetch")) {
    fatal(`could not connect to server at ${SERVER_URL}. Is it running?`);
  }
  fatal(msg);
});
